{% set name = "logrun" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/logrun-{{ version }}.tar.gz
  sha256: 2a7c96fa05315c1186e6649a6de679ac71c293aa2e2b0fdbbf3994ab45b26f08

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dill
    - git
    - gitpython
    - psutil
    - python >=3.6
    - python-xxhash

test:
  imports:
    - logrun
    - logrun.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dccsillag/logrun
  summary: A convenient experiment logging package for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dccsillag
