{% set name = "logrun" %}
{% set version = "0.1.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/logrun-{{ version }}.tar.gz
  sha256: 20c40bae0146f572455feed6133ec8b8def2de23f1ddf8fd2beab348d1130038

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - dill
    - git
    - gitpython
    - psutil
    - python >=3.6
    - python-xxhash

test:
  imports:
    - logrun
    - logrun.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/dccsillag/logrun
  summary: A convenient experiment logging package for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dccsillag
